import { type TeamData } from "@/app/types";
import Pic1 from "public/images/background.jpg";

export const teamData: TeamData[] = [
  {
    name: "Player one",
    role: "convenor",
    image: Pic1,
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    email: "b23295@students.iitmandi.ac.in",
    phone: "9043674629",
    linkedin: "shubham-s-padhi",
    instagram: "shubum_27",
  },
  {
    name: "Player two",
    role: "co-convenor",
    image: Pic1,
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    email: "b23295@students.iitmandi.ac.in",
    phone: "9043674629",
    linkedin: "shubham-s-padhi",
    instagram: "shubum_27",
  },
  {
    name: "Player three",
    role: "head",
    org: "web dev",
    image: Pic1,
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    email: "b23295@students.iitmandi.ac.in",
    phone: "9043674629",
    linkedin: "shubham-s-padhi",
    instagram: "shubum_27",
  },
  {
    name: "Player four",
    role: "head",
    org: "web dev",
    image: Pic1,
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    email: "b23295@students.iitmandi.ac.in",
    phone: "9043674629",
    linkedin: "shubham-s-padhi",
    instagram: "shubum_27",
  },
  {
    name: "Player five",
    role: "head",
    org: "design",
    image: Pic1,
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    email: "b23295@students.iitmandi.ac.in",
    phone: "9043674629",
    linkedin: "shubham-s-padhi",
    instagram: "shubum_27",
  },
  {
    name: "Player six",
    role: "head",
    org: "design",
    image: Pic1,
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    email: "b23295@students.iitmandi.ac.in",
    phone: "9043674629",
    linkedin: "shubham-s-padhi",
    instagram: "shubum_27",
  },
];
